# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
---
minimum_pre_commit_version: 3.3.0
default_install_hook_types: [pre-commit,commit-msg]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-executables-have-shebangs
      - id: mixed-line-ending
        args: ['-f=lf']
      - id: double-quote-string-fixer

  - repo: https://github.com/espressif/conventional-precommit-linter
    rev: v1.2.0
    hooks:
      - id: conventional-precommit-linter
        stages: [commit-msg]

  - repo: https://github.com/espressif/check-copyright/
    rev: v1.1.0
    hooks:
      - id: check-copyright
        args: ['--config', 'check_copyright_config.yaml']

  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: make clang-format
        language: system
        pass_filenames: false
